pkgname <- "Rsagacmd"
source(file.path(R.home("share"), "R", "examples-header.R"))
options(warn = 1)
library('Rsagacmd')

base::assign(".oldSearch", base::search(), pos = 'CheckExEnv')
base::assign(".old_wd", base::getwd(), pos = 'CheckExEnv')
cleanEx()
nameEx("Rsagacmd")
### * Rsagacmd

flush(stderr()); flush(stdout())

### Name: Rsagacmd
### Title: Rsagacmd: Linking R with the open-source SAGA-GIS software.
### Aliases: Rsagacmd Rsagacmd-package
### Keywords: internal

### ** Examples

## Not run: 
##D library(Rsagacmd)
##D library(magrittr)
##D 
##D # initialize a saga object
##D saga <- saga_gis(opt_lib = c("grid_calculus", "ta_morphometry"))
##D 
##D # example of executing a tool using a tempfile to store the tool outputs
##D dem <- saga$grid_calculus$random_terrain(radius = 100, iterations = 500)
##D 
##D # Example of chaining operations using pipes and using tempfile to
##D # store tool outputs
##D tri <- dem %>%
##D   saga$ta_morphometry$terrain_ruggedness_index_tri()
##D 
##D # Remove tempfiles generated by Rsagacmd during a session
##D saga_remove_tmpfiles(h = 0)
## End(Not run)



cleanEx()
nameEx("mrvbf_threshold")
### * mrvbf_threshold

flush(stderr()); flush(stdout())

### Name: mrvbf_threshold
### Title: Calculate the t_slope value based on DEM resolution for MRVBF
### Aliases: mrvbf_threshold

### ** Examples

mrvbf_threshold(res = 10)



cleanEx()
nameEx("print.saga_tool")
### * print.saga_tool

flush(stderr()); flush(stdout())

### Name: print.saga_tool
### Title: Generic function to display help and usage information for any
###   SAGA-GIS tool
### Aliases: print.saga_tool

### ** Examples

## Not run: 
##D # Initialize a saga object
##D saga <- saga_gis()
##D 
##D # Display usage information on a tool
##D print(saga$ta_morphometry$slope_aspect_curvature)
##D 
##D # Or simply:
##D saga$ta_morphometry$slope_aspect_curvature
## End(Not run)



cleanEx()
nameEx("read_srtm")
### * read_srtm

flush(stderr()); flush(stdout())

### Name: read_srtm
### Title: Get path to the example DEM data
### Aliases: read_srtm

### ** Examples

library(Rsagacmd)
library(terra)

dem <- read_srtm()
plot(dem)



cleanEx()
nameEx("saga_docs")
### * saga_docs

flush(stderr()); flush(stdout())

### Name: saga_docs
### Title: Browse the online documentation for a saga_tool
### Aliases: saga_docs

### ** Examples

## Not run: 
##D library(Rsagacmd)
##D 
##D saga <- saga_gis()
##D 
##D saga_docs(saga$ta_morphometry$slope_aspect_curvature)
## End(Not run)



cleanEx()
nameEx("saga_gis")
### * saga_gis

flush(stderr()); flush(stdout())

### Name: saga_gis
### Title: Initiate a SAGA-GIS geoprocessor object
### Aliases: saga_gis

### ** Examples

## Not run: 
##D # Initialize a saga object
##D library(Rsagacmd)
##D library(terra)
##D 
##D saga <- saga_gis()
##D 
##D # Alternatively initialize a saga object using file caching to handle large
##D # raster files
##D saga <- saga_gis(grid_caching = TRUE, grid_cache_threshold = 250, cores = 1)
##D 
##D # Example terrain analysis
##D # Generate a random DEM
##D dem <- saga$grid_calculus$random_terrain(radius = 100)
##D 
##D # Use Rsagacmd to calculate the Terrain Ruggedness Index
##D tri <- saga$ta_morphometry$terrain_ruggedness_index_tri(dem = dem)
##D plot(tri)
##D 
##D # Optionally run command and do not load result as an R object
##D saga$ta_morphometry$terrain_ruggedness_index_tri(dem = dem, .intern = FALSE)
##D 
##D # Initialize a saga object but do not automatically save all results to
##D # temporary files to load into R. Use this if you are explicitly saving each
##D # output because this will save disk space by not saving results from tools
##D # that output multiple results that you may be want to keep.
##D saga <- saga_gis(all_outputs = FALSE)
## End(Not run)



cleanEx()
nameEx("saga_remove_tmpfiles")
### * saga_remove_tmpfiles

flush(stderr()); flush(stdout())

### Name: saga_remove_tmpfiles
### Title: Removes temporary files created by Rsagacmd
### Aliases: saga_remove_tmpfiles

### ** Examples

## Not run: 
##D # Remove all temporary files generated by Rsagacmd
##D saga_remove_tmpfiles(h = 0)
## End(Not run)



cleanEx()
nameEx("saga_show_tmpfiles")
### * saga_show_tmpfiles

flush(stderr()); flush(stdout())

### Name: saga_show_tmpfiles
### Title: List temporary files created by Rsagacmd
### Aliases: saga_show_tmpfiles

### ** Examples

## Not run: 
##D # Show all temporary files generated by Rsagacmd
##D saga_remove_tmpfiles(h = 0)
## End(Not run)



cleanEx()
nameEx("search_tools")
### * search_tools

flush(stderr()); flush(stdout())

### Name: search_tools
### Title: Search for a SAGA-GIS tool
### Aliases: search_tools

### ** Examples

## Not run: 
##D # initialize Rsagacmd
##D saga <- saga_gis()
##D 
##D # search for a tool
##D search_tools(x = saga, pattern = "terrain")
## End(Not run)



cleanEx()
nameEx("show_raster_formats")
### * show_raster_formats

flush(stderr()); flush(stdout())

### Name: show_raster_formats
### Title: List the available raster formats that can be set as defaults
###   for a 'saga' object.
### Aliases: show_raster_formats

### ** Examples

show_raster_formats()



cleanEx()
nameEx("show_vector_formats")
### * show_vector_formats

flush(stderr()); flush(stdout())

### Name: show_vector_formats
### Title: List the available vector formats that can be set as defaults
###   for a 'saga' object.
### Aliases: show_vector_formats

### ** Examples

show_vector_formats()



cleanEx()
nameEx("tidy.saga")
### * tidy.saga

flush(stderr()); flush(stdout())

### Name: tidy.saga
### Title: Summarize the libraries that are available within a saga object
###   and return these as a tibble.
### Aliases: tidy.saga

### ** Examples

## Not run: 
##D # Initialize a saga object
##D saga <- saga_gis()
##D 
##D # tidy the saga object's parameters into a tibble
##D tidy(saga)
## End(Not run)



cleanEx()
nameEx("tidy.saga_library")
### * tidy.saga_library

flush(stderr()); flush(stdout())

### Name: tidy.saga_library
### Title: Summarize the tools that are available within a saga library and
###   return these as a tibble.
### Aliases: tidy.saga_library

### ** Examples

## Not run: 
##D # Initialize a saga object
##D saga <- saga_gis()
##D 
##D # tidy the library's parameters into a tibble
##D tidy(saga$climate_tools)
## End(Not run)



cleanEx()
nameEx("tidy.saga_tool")
### * tidy.saga_tool

flush(stderr()); flush(stdout())

### Name: tidy.saga_tool
### Title: Summarize the parameters that are available within a SAGA-GIS
###   tool and return these as a tibble.
### Aliases: tidy.saga_tool

### ** Examples

## Not run: 
##D # Initialize a saga object
##D saga <- saga_gis()
##D 
##D # tidy the tools parameters into a tibble
##D tidy(saga$ta_morphometry$slope_aspect_curvature)
## End(Not run)



cleanEx()
nameEx("tile_geoprocessor")
### * tile_geoprocessor

flush(stderr()); flush(stdout())

### Name: tile_geoprocessor
### Title: Split a raster grid into tiles for tile-based processing
### Aliases: tile_geoprocessor

### ** Examples

## Not run: 
##D # Initialize a saga object
##D saga <- saga_gis()
##D 
##D # Generate a random DEM
##D dem <- saga$grid_calculus$random_terrain(radius = 15, iterations = 500)
##D 
##D # Return tiled version of DEM
##D tiles <- tile_geoprocessor(x = saga, grid = dem, nx = 20, ny = 20)
## End(Not run)



### * <FOOTER>
###
cleanEx()
options(digits = 7L)
base::cat("Time elapsed: ", proc.time() - base::get("ptime", pos = 'CheckExEnv'),"\n")
grDevices::dev.off()
###
### Local variables: ***
### mode: outline-minor ***
### outline-regexp: "\\(> \\)?### [*]+" ***
### End: ***
quit('no')
